---
prometheus_instances:
  - instance_number: '01'
    namespace: metrics
    mimir_url: http://mimir-service.metrics.svc.cluster.local:9009/api/v1/push
    scrape_interval: 60s
    evaluation_interval: 60s
    rule_files: |
      rule_files:
        # - "first.rules"
        # - "second.rules"
    scrape_configs: |
      scrape_configs:
        - job_name: prometheus-01
          honor_labels: true
          static_configs:
            - targets: ['localhost:9090']

        - job_name: configmgr
          honor_labels: true
          static_configs:
            - targets:
              - 'serverA.example.com:9182'
              - 'serverB.example.com:9182'
              - 'serverC.example.com:9182'
              - 'serverD.example.com:9182'

        - job_name: ansible-controller-prod
          tls_config:
            insecure_skip_verify: true
          metrics_path: /api/v2/metrics
          scrape_interval: 10s
          scheme: https
          bearer_token: {{ lookup('keepersecurity.keeper_secrets_manager.keeper', title='ansible-controller-prod-metrics-api', custom_field='Token') }}
          static_configs:
            - targets: ['ansible.example.com:443']

        - job_name: adfs-prod
          honor_labels: true
          static_configs:
            - targets:
                - 'serverD.ilstu.edu:9273'
                - 'XXX.XXX.XXX.XXX:9273'

        - job_name: mimir
          honor_labels: true
          static_configs:
            - targets: ['mimir-service.metrics.svc.cluster.local:9009']
